# Generated by Django 3.2.4 on 2022-02-16 04:24

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('half_size', 'Half Size'), ('full_size', 'Full Size')], max_length=255, verbose_name='Type')),
                ('price', models.FloatField(max_length=255, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('size', models.CharField(choices=[('double_extra_large', 'XXL'), ('extra_large', 'XL'), ('large', 'L'), ('medium', 'M'), ('small', 'S')], max_length=255, verbose_name='Size')),
                ('color_code', models.CharField(max_length=50, verbose_name='Color')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'db_table': 'tshirt',
            },
        ),
    ]
