# Generated by Django 3.2.4 on 2022-02-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='password',
        ),
    ]
