# Generated by Django 3.2.4 on 2022-02-16 05:04

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logos', '0001_initial'),
        ('tshirts', '0002_remove_tshirt_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255, verbose_name='Gender')),
                ('price', models.FloatField(max_length=255, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logos.logo')),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tshirts.tshirt')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
